"""
Copyright (c) 2021-, Haibin Wen, sunnypilot, and a number of other contributors.

This file is part of sunnypilot and is licensed under the MIT License.
See the LICENSE.md file in the root directory for more details.
"""

# Preglobal Subarus have no LKAS button, so MADS has no dedicated lateral toggle
# (see opendbc/sunnypilot/car/subaru/mads.py, which only reads ES_LKAS_State on global cars).
# The only lateral toggle the driver has is the ACC main (cruise ON/OFF) button, which MADS
# picks up through cruiseState.available.
#
# The preglobal carcontroller mocks a main button press whenever main is off and the car is
# past its start-up state. That press is also how openpilot cancels ACC on this platform, so
# it can't simply be removed: cancel presses main off, and the same code presses it back on.
# The side effect is that a driver pressing main off gets it turned straight back on, which
# blips MADS lateral off and immediately back on instead of latching it off.
#
# This tracks who turned main off, so openpilot only restores main when openpilot is the one
# that turned it off.

# How long we wait for a mocked press to land before giving up on it. The carcontroller runs
# at 100Hz, so this is ~1s. A main state change inside this window is ours, not the driver's.
MAIN_CRUISE_PRESS_TIMEOUT_FRAMES = 100


class PreglobalMainCruise:
  def __init__(self):
    self.available_prev = False
    self.driver_turned_off = False
    self.pending_press_frame: int | None = None
    self.driver_press_frame: int | None = None
    self.driver_press_wants_off = False
    self.driver_button_prev = False

  def update(self, frame: int, available: bool, driver_main_pressed: bool = False) -> None:
    press_in_flight = self.pending_press_frame is not None and \
                      (frame - self.pending_press_frame) < MAIN_CRUISE_PRESS_TIMEOUT_FRAMES
    driver_press_in_flight = self.driver_press_frame is not None and \
                             (frame - self.driver_press_frame) < MAIN_CRUISE_PRESS_TIMEOUT_FRAMES

    # The availability bit can move on the same frame as the raw button, or a few frames later.
    # Remember the state at the physical button's rising edge so pcm_cancel_cmd generated by that
    # same transition cannot make us claim the driver's press as our own.
    driver_press_rising = driver_main_pressed and not self.driver_button_prev
    if driver_press_rising:
      self.driver_press_frame = frame
      self.driver_press_wants_off = available
      self.driver_turned_off = self.driver_press_wants_off
      self.pending_press_frame = None
      press_in_flight = False
      driver_press_in_flight = True

    if self.available_prev != available:
      if driver_press_in_flight:
        self.driver_turned_off = not available
        self.driver_press_frame = None
      elif press_in_flight:
        # our own mocked press landed, whichever way main moved
        self.pending_press_frame = None
      elif not available:
        # main went off and openpilot didn't ask for it: the driver pressed ACC main
        self.driver_turned_off = True

    if available and self.driver_press_frame is None:
      self.driver_turned_off = False

    if self.driver_press_frame is not None and not driver_press_in_flight:
      self.driver_press_frame = None

    self.available_prev = available
    self.driver_button_prev = driver_main_pressed

  def should_restore(self, available: bool, ready: bool) -> bool:
    return not available and ready and not self.driver_turned_off

  def mocked_press(self, frame: int) -> None:
    self.pending_press_frame = frame
